-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agent_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  payload jsonb DEFAULT '{}'::jsonb,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.approval_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reviewer_id uuid NOT NULL,
  brief_id uuid,
  content_item_id uuid,
  asset_id uuid,
  decision USER-DEFINED NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT approval_events_pkey PRIMARY KEY (id),
  CONSTRAINT approval_events_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.team_members(id),
  CONSTRAINT approval_events_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id),
  CONSTRAINT approval_events_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  brief_id uuid,
  content_item_id uuid,
  job_id uuid,
  asset_type USER-DEFINED NOT NULL,
  storage_path text NOT NULL,
  public_url text,
  filename text NOT NULL,
  mime_type text NOT NULL,
  file_size_bytes bigint,
  generation_prompt text,
  generator text,
  generator_job_id text,
  approval_status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  platform USER-DEFINED,
  format USER-DEFINED,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  analysis_status text DEFAULT 'pending'::text,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT assets_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id),
  CONSTRAINT assets_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT assets_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.team_members(id),
  CONSTRAINT assets_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.team_members(id)
);
CREATE TABLE public.brand_contexts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  version integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  source_file_path text,
  context_json jsonb NOT NULL,
  token_count integer,
  processed_by text NOT NULL DEFAULT 'system'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  content jsonb,
  CONSTRAINT brand_contexts_pkey PRIMARY KEY (id),
  CONSTRAINT brand_contexts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id)
);
CREATE TABLE public.budget_alerts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  allocation_id uuid NOT NULL,
  alert_type text NOT NULL,
  threshold_pct numeric,
  message text NOT NULL,
  is_resolved boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT budget_alerts_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.budget_allocations(id)
);
CREATE TABLE public.budget_allocations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  platform USER-DEFINED NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  allocated_usd numeric NOT NULL CHECK (allocated_usd > 0::numeric),
  spent_usd numeric NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT budget_allocations_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT budget_allocations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(id)
);
CREATE TABLE public.calendar_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  brief_id uuid NOT NULL,
  content_item_id uuid,
  asset_id uuid,
  platform USER-DEFINED NOT NULL,
  format USER-DEFINED NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  published_at timestamp with time zone,
  content_status USER-DEFINED NOT NULL DEFAULT 'approved'::content_status,
  platform_post_id text,
  platform_ad_id text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT calendar_entries_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_entries_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT calendar_entries_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id),
  CONSTRAINT calendar_entries_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT calendar_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(id)
);
CREATE TABLE public.concepts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key USER-DEFINED NOT NULL UNIQUE,
  name text NOT NULL,
  identity_colour text NOT NULL,
  audience_focus text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT concepts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.content_briefs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  research_brief_id uuid,
  job_id uuid,
  platform USER-DEFINED NOT NULL,
  format USER-DEFINED NOT NULL,
  content_angle text NOT NULL,
  hook text NOT NULL,
  call_to_action text NOT NULL,
  visual_direction text,
  notes text,
  target_publish_date date,
  approval_status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  revision_notes text,
  content_status USER-DEFINED NOT NULL DEFAULT 'ideation'::content_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  research_summary text,
  market_data jsonb,
  agent_brief text,
  ideation_job_id uuid,
  production_job_id uuid,
  code text,
  stage text NOT NULL DEFAULT 'ideation'::text,
  assignee text,
  comments integer NOT NULL DEFAULT 0,
  attachments integer NOT NULL DEFAULT 0,
  due_date timestamp with time zone,
  CONSTRAINT content_briefs_pkey PRIMARY KEY (id),
  CONSTRAINT content_briefs_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT content_briefs_research_brief_id_fkey FOREIGN KEY (research_brief_id) REFERENCES public.research_briefs(id),
  CONSTRAINT content_briefs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT content_briefs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.team_members(id),
  CONSTRAINT content_briefs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(id)
);
CREATE TABLE public.content_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  brief_id uuid NOT NULL,
  job_id uuid,
  type text NOT NULL DEFAULT 'concept'::text CHECK (type = ANY (ARRAY['concept'::text, 'draft'::text, 'final'::text])),
  platform text,
  title text,
  headline text,
  caption text,
  body text,
  channels ARRAY,
  rationale text,
  metadata jsonb DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'rejected'::text])),
  scheduled_at timestamp with time zone,
  asset_ids ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_items_pkey PRIMARY KEY (id),
  CONSTRAINT content_items_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id)
);
CREATE TABLE public.feedback_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  author_id uuid NOT NULL,
  brief_id uuid,
  content_item_id uuid,
  parent_id uuid,
  body text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feedback_comments_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.team_members(id),
  CONSTRAINT feedback_comments_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id),
  CONSTRAINT feedback_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.feedback_comments(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid,
  agent_type USER-DEFINED NOT NULL DEFAULT 'ideation'::agent_type,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::job_status,
  parent_job_id uuid,
  input_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_payload jsonb,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  max_retries integer NOT NULL DEFAULT 2,
  triggered_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  payload jsonb,
  task text,
  result jsonb,
  error text,
  attempts integer DEFAULT 0,
  finished_at timestamp with time zone,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT jobs_parent_job_id_fkey FOREIGN KEY (parent_job_id) REFERENCES public.jobs(id),
  CONSTRAINT jobs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES public.team_members(id)
);
CREATE TABLE public.member_concept_access (
  member_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  CONSTRAINT member_concept_access_pkey PRIMARY KEY (member_id, concept_id),
  CONSTRAINT member_concept_access_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.team_members(id),
  CONSTRAINT member_concept_access_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipient_id uuid NOT NULL,
  channel USER-DEFINED NOT NULL DEFAULT 'email'::notification_channel,
  brief_id uuid,
  content_item_id uuid,
  job_id uuid,
  subject text NOT NULL,
  body text NOT NULL,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.team_members(id),
  CONSTRAINT notifications_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES public.content_briefs(id),
  CONSTRAINT notifications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.platform_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform text NOT NULL UNIQUE CHECK (platform = ANY (ARRAY['meta'::text, 'linkedin'::text, 'google_ads'::text])),
  access_token text,
  account_name text,
  is_active boolean NOT NULL DEFAULT true,
  page_id text,
  ig_user_id text,
  org_id text,
  developer_token text,
  customer_id text,
  campaign_id text,
  ad_group_id text,
  final_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_credentials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_data_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  concept_id uuid NOT NULL,
  platform text NOT NULL,
  snapshot_date date NOT NULL,
  summary_json jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_data_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT platform_data_snapshots_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.published_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_item_id uuid,
  concept_id uuid,
  platform text NOT NULL,
  platform_post_id text,
  platform_post_url text,
  status text NOT NULL DEFAULT 'published'::text CHECK (status = ANY (ARRAY['published'::text, 'failed'::text, 'scheduled'::text])),
  error_message text,
  published_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT published_posts_pkey PRIMARY KEY (id),
  CONSTRAINT published_posts_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.content_items(id),
  CONSTRAINT published_posts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id)
);
CREATE TABLE public.research_briefs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  concept_id uuid NOT NULL,
  job_id uuid,
  week_start date NOT NULL,
  opportunities jsonb NOT NULL,
  raw_data_snapshot jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT research_briefs_pkey PRIMARY KEY (id),
  CONSTRAINT research_briefs_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id),
  CONSTRAINT research_briefs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
